language: cpp
compiler: gcc
os: osx
before_install:
  - pip install --user cpp-coveralls
script:
  - cmake -S . -B build -DCMAKE_CXX_FLAGS="-ftest-coverage -fprofile-arcs"
  - make -C build
  - ./simple-equation-solver-tests
after_success:
  ~/Library/Python/2.7/bin/cpp-coveralls --root . -E ".*CMakeFiles.*" -i includes -i srcs/SolverLib
