language: cpp
compiler: gcc
os: osx
before_install:
  - pip install cpp-coveralls
script:
  - cmake -DFTEST_COVERAGE=1 .
  - make
  - ./GTests
after_success:
  - coveralls --root . -E ".*CMakeFiles.*"