language: cpp
compiler: clang
os: osx
before_install:
  - pip install cpp-coveralls
script:
  - cmake -DFTEST_COVERAGE .
  - make
  - ./GTests
after_success:
  - coveralls --root . -E ".*CMakeFiles.*"