language: cpp
compiler: gcc
os: osx
before_install:
  - pip install cpp-coveralls
script:
  - cmake -DCMAKE_CXX_FLAGS="-ftest-coverage" .
  - make
  - ./GTests
after_success:
  - coveralls --root . -E ".*CMakeFiles.*"